[package]
name = "swarm_control_proto"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.13"
tonic = { version = "0.12", features = ["prost"] }

[build-dependencies]
tonic-build = "0.12"
protoc-bin-vendored = "3"

